on: push
jobs:
  first_job:
    runs-on: ubuntu-latest
    container: node:17.6.0
    steps:
      - run: node --version
      - run: npm --version
  build_node:
    runs-on: ubuntu-latest
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v3
      - run: npm install 
      - run: node index.js
